{{- if not .Values.persistence.state.hostPath }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openclaw-role.fullname" . }}-state
  namespace: {{ .Values.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.state.size }}
{{- end }}
{{- if not .Values.persistence.workspace.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openclaw-role.fullname" . }}-workspace
  namespace: {{ .Values.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.workspace.size }}
{{- end }}
